### ISSUE TITLE
소셜 로그인 리팩토링

### ISSUE THREAD

**Issue by don9m1n** [reading-log/backend#18]
- 서로 다른 플랫폼인 경우에도 같은 이메일을 쓰는 경우가 있음.
- 다른 플랫폼이여도 이메일이 같으면 가입된 회원으로 인식해버리는 버그 발견...

**Comment by enjoy89** [comment]
사용자의 이메일과 소셜 로그인 플랫폼 정보를 조합하여 사용자를 구분하는 방법이 좋을거같은데, 어떻게 생각하시나요?

**Comment by don9m1n** [comment]
> 사용자의 이메일과 소셜 로그인 플랫폼 정보를 조합하여 사용자를 구분하는 방법이 좋을거같은데, 어떻게 생각하시나요?

그것도 좋을 것 같고, role 컬럼에 KAKAO, NAVER, GOOGLE을 추가해서 구분해도 좋을 것 같습니다.
`findByEmailAndRole()` 메서드로 구분이 되지 않을까 싶네용

**Comment by enjoy89** [comment]
넵 말씀해주신 부분처럼 새로 `login_platform` 이름으로 **KAKAO, NAVER, GOOGLE** 값들을 enum으로 저장해두고, `findByEmailAndLoginPlatform` 메서드로 유저를 찾도록 해보겠습니다!

**Comment by enjoy89** [comment]
+스프링 시큐리티는 이메일 로그인 시 역할(권한)을 설정하는 로직에서 **"ROLE_" 접두사**가 붙어, DB에서 `email`+`memberRole`을 이용하여 사용자를 조회할 때 제대로 동작하지 않는 버그 발견

**Comment by don9m1n** [comment]
> +스프링 시큐리티는 이메일 로그인 시 역할(권한)을 설정하는 로직에서 **"ROLE_" 접두사**가 붙어, DB에서 `email`+`memberRole`을 이용하여 사용자를 조회할 때 제대로 동작하지 않는 버그 발견

위키에 써놨습니다 ㅋㅋㅋㅋ
